[workspace]
members = ["src/api", "src/db"]

[workspace.dependencies]
common = { path = "../common", features = ["backend"] }
serde = { version = "1.0.152", features = ["serde_derive", "derive"] }
serde_json = "1.0.91"
sqlx = { version = "0.6.3", features = ["postgres", "json", "runtime-tokio-rustls", "uuid"] }
anyhow = "1.0.68"
axum-login = { version = "0.5.0", features = ["postgres"] }
