[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
anyhow = "1.0.68"
serde = { version = "1.0.152", features = ["serde_derive", "derive"] }
serde_json = "1.0.91"
sqlx = { version = "0.6.2", features = ["postgres", "json", "runtime-tokio-native-tls"] }
tokio = { version = "1.24.1", features = ["full"] }
env_logger = "0.9.1"
actix-identity = "0.5.2"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
log = "0.4.17"
actix-cors = "0.6.4"
actix-web-grants = "3.0.1"
futures-util = "0.3.25"
sha2 = "0.10.6"
