[package]
name = "form_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
form_derive_impl = { path = "./form_derive_impl" }
form_derive_trait = { path = "./form_derive_trait" }
