//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "unit")]
pub enum Unit {
    #[sea_orm(string_value = "clove")]
    Clove,
    #[sea_orm(string_value = "cup")]
    Cup,
    #[sea_orm(string_value = "deciliter")]
    Deciliter,
    #[sea_orm(string_value = "gram")]
    Gram,
    #[sea_orm(string_value = "hectogram")]
    Hectogram,
    #[sea_orm(string_value = "kilogram")]
    Kilogram,
    #[sea_orm(string_value = "liter")]
    Liter,
    #[sea_orm(string_value = "milligram")]
    Milligram,
    #[sea_orm(string_value = "milliliter")]
    Milliliter,
    #[sea_orm(string_value = "pinch")]
    Pinch,
    #[sea_orm(string_value = "tablespoon")]
    Tablespoon,
    #[sea_orm(string_value = "teaspoon")]
    Teaspoon,
}
