version: "3.8"
services:
  # foodie_frontend:
  #   container_name: foodie_frontend
  #   hostname: foodie_frontend
  #   tty: true
  #   build:
  #     context: ../frontend
  #     dockerfile: .docker/Dockerfile
  #   restart: always
  #   volumes:
  #     - ../frontend:/app
  #   network_mode: host
  #   # ports:
  #   #   - "8080:8080"
  #   depends_on:
  #     - foodie_backend

  # foodie_backend:
  #   container_name: foodie_backend
  #   hostname: foodie_backend
  #   build:
  #     context: ../backend
  #     dockerfile: .docker/Dockerfile
  #   restart: always
  #   depends_on:
  #     - postgres
  #   tty: true
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ../backend/src:/app/src
  #     - ../backend/migrations:/app/migrations
  #     - ../.db/filestorage:/.filestorage
  #     - ../backend/Cargo.toml:/app/Cargo.toml
  #   environment:
  #     - FOODIE_SECRET_KEY=$FOODIE_SECRET_KEY
  #     - POSTGRES_HOST=foodie_postgres:5432
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - DATABASE_URL=postgres://postgres:postgres@foodie_postgres:5432

  postgres:
    hostname: foodie_postgres
    container_name: foodie_postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ../.db/foodie_db:/var/lib/postgresql/data

  localstack:
    container_name: foodie_localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
      - EXTRA_CORS_ALLOWED_ORIGINS=*
    volumes:
      - "../.db/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ../.aws:/etc/localstack/init/ready.d
