FROM rust:bookworm as builder

WORKDIR /app

COPY common/Cargo.toml common/Cargo.lock ../common/
COPY common/src ../common/src

COPY backend/Cargo.toml backend/Cargo.lock ./
COPY backend/src ./src
COPY backend/migration ./migration

RUN cargo build --release

FROM debian:bookworm-slim AS runtime
WORKDIR /app
RUN apt-get update && apt install -y openssl ca-certificates
COPY --from=builder /app/target/release/backend /usr/local/bin
ENTRYPOINT ["/usr/local/bin/backend"]
