name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.0.1
        with:
          cache-on-failure: "false"
          workspaces: |
            backend
            frontend

      - name: Build frontend
        working-directory: frontend
        run: cargo build

      - name: Build backend
        working-directory: backend
        run: cargo build

      - name: Run tests in backend
        working-directory: backend
        run: cargo test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          # Dummy env-variables. Creates a client on setup, but doesn't use it in tests
          GOOGLE_CLIENT_ID: "foo"
          GOOGLE_CLIENT_SECRET: "foo"
          FRONTEND_URL: "foo"
          BASE_URL: "foo"
