name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  frontend-build:
    steps:
      - uses: ./.github/actions/setup_rust

      - name: Build frontend
        working-directory: frontend
        run: cargo build

  backend-build:
    steps:
      - uses: ./.github/actions/setup_rust

      - name: Build backend
        working-directory: backend
        run: cargo build

  backend-test:
    needs: backend-build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: ./.github/actions/setup_rust
      - name: Run tests in backend
        working-directory: backend
        run: cargo test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          # Dummy env-variables. Creates a client on setup, but doesn't use it in tests
          GOOGLE_CLIENT_ID: "foo"
          GOOGLE_CLIENT_SECRET: "foo"
          FRONTEND_URL: "https://example.com"
          BASE_URL: "https://example.com"
