name: Setup Rust

on:
  workflow_call:

jobs:
  rust-setup:
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.0.1
        with:
          cache-on-failure: "false"
          workspaces: |
            backend
            frontend
